### ISSUE TITLE
Support for lapack 3.9.1

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/intel_repack-feedstock#24]
Following up from #6, there shouldn't be much (if anything) to be compatible with in addition to 3.9.0. Still, perhaps @oleksandr-pavlyk could shed some light if MKL claims (or when it will) compatibility with 3.9.1

Xref:
https://github.com/conda-forge/lapack-feedstock/pull/51
https://github.com/conda-forge/blas-feedstock/pull/70

**Comment by sknepper** [comment]
The currently-released Intel oneMKL 2021.2 is generally compatible with LAPACK 3.9.1, except for ?GGEV routines, due to algorithmic changes of the QZ algorithm in LAPACK 3.9.1.  We plan to support LAPACK 3.9.1 no sooner than in Intel oneMKL 2021.4.

Is there a particular change in LAPACK 3.9.1 that you are interested in?  Thanks!

**Comment by h-vetinari** [comment]
Hey @sknepper, thanks for the response!

The interest is mainly in the context of supporting 3.9.1. in conda-forge (which supports several blas variants, so it would make things easiest if all versions actually have explicit support).

**Comment by h-vetinari** [comment]
> We plan to support LAPACK 3.9.1 no sooner than in Intel oneMKL 2021.4.

@sknepper Is there an ETA or timeline for 2021.4?

**Comment by sknepper** [comment]
As mentioned elsewhere, based on the changes in LAPACK 3.9.1 (more than just simple bug fixes), and the release of LAPACK 3.10, we decided to align to LAPACK 3.10 directly. The soonest that would be supported would be in Intel oneMKL 2022.1. The oneMKL release notes will include this change once it is made.
